/**
 * Pure Domain Contracts for Generative Audio Studio:
 * - Voiceover (TTS via Gemini 3.1 Flash TTS)
 * - Music Generation (Lyria 3.5 Clip / Pro)
 */

import type { BrandContextSnapshot } from "./textGeneration.js";

export interface AudioAssetReference {
  id: string;
  name?: string;
  mimeType: string;
  dataBase64?: string;
  url?: string;
}

export type AudioGenerationType = "voiceover" | "music";

export type OfficialGeminiVoice =
  | "Zephyr"
  | "Puck"
  | "Charon"
  | "Kore"
  | "Fenrir"
  | "Leda"
  | "Orus"
  | "Aoede"
  | "Callirrhoe"
  | "Autonoe"
  | "Enceladus"
  | "Iapetus"
  | "Umbriel"
  | "Algieba"
  | "Despina"
  | "Erinome"
  | "Algenib"
  | "Rasalgethi"
  | "Laomedeia"
  | "Achernar"
  | "Alnilam"
  | "Schedar"
  | "Gacrux"
  | "Pulcherrima"
  | "Achird"
  | "Zubenelgenubi"
  | "Vindemiatrix"
  | "Sadachbia"
  | "Sadaltager"
  | "Sulafat";

export const OFFICIAL_GEMINI_VOICES: readonly OfficialGeminiVoice[] = [
  "Zephyr",
  "Puck",
  "Charon",
  "Kore",
  "Fenrir",
  "Leda",
  "Orus",
  "Aoede",
  "Callirrhoe",
  "Autonoe",
  "Enceladus",
  "Iapetus",
  "Umbriel",
  "Algieba",
  "Despina",
  "Erinome",
  "Algenib",
  "Rasalgethi",
  "Laomedeia",
  "Achernar",
  "Alnilam",
  "Schedar",
  "Gacrux",
  "Pulcherrima",
  "Achird",
  "Zubenelgenubi",
  "Vindemiatrix",
  "Sadachbia",
  "Sadaltager",
  "Sulafat",
] as const;

export interface SpeakerDefinition {
  name: string; // e.g. "Host" or "Speaker 1"
  voice: OfficialGeminiVoice;
  role?: string;
}

export interface VoiceConfig {
  speakerMode: "single" | "two-speaker";
  speakers: [SpeakerDefinition] | [SpeakerDefinition, SpeakerDefinition];
}

export type VoiceEmotion =
  | "Neutral"
  | "Professional"
  | "Cheerful"
  | "Energetic"
  | "Calming"
  | "Dramatic"
  | "Authoritative";

export type VoicePace = "normal" | "fast" | "deliberate" | "slow";

export interface PerformanceConfig {
  emotion?: VoiceEmotion;
  pace?: VoicePace;
  accent?: string; // e.g. "Indian English", "Hinglish", "British RP", "Neutral American"
  style?: string; // e.g. "cinematic trailer", "podcast interview", "commercial promo"
  tagsEnabled?: boolean;
}

export interface VoiceoverRequest {
  generationType: "voiceover";
  userIntent: string;
  brandContext?: BrandContextSnapshot;
  transcript?: string; // If supplied, directly synthesized; if not, generated by Scriptwriter
  languageCode?: string; // BCP-47 e.g. "en-US", "hi-IN", "gu-IN", "mr-IN"
  targetDurationSeconds?: number;
  voiceConfig: VoiceConfig;
  performanceConfig?: PerformanceConfig;
  idempotencyKey?: string;
}

export interface VoiceoverResult {
  audioBase64: string;
  mimeType: "audio/wav" | "audio/mpeg" | "audio/mp3";
  transcript: string;
  durationSeconds: number;
  voice: OfficialGeminiVoice | string;
  speakers: SpeakerDefinition[];
  modelUsed: string;
  provider?: "google" | "fal";
  storageUrl?: string;
  storagePath?: string;
  failoverState?: {
    primaryProvider: "google" | "fal";
    primaryModel: string;
    fallbackUsed: boolean;
    fallbackProvider?: "google" | "fal";
    fallbackModel?: string;
    fallbackReason?: string;
    retryCount: number;
    providerRequestId?: string;
  };
  providerCost?: {
    amount: number;
    currency: string;
    billingUnit: string;
  };
}

export type MusicMode = "clip" | "full-track";

export interface MusicRequest {
  generationType: "music";
  prompt: string;
  mode: MusicMode;
  genre?: string;
  mood?: string;
  tempoBpm?: number;
  keyScale?: string;
  instrumentation?: string[];
  vocalsMode?: "instrumental" | "with-vocals";
  lyrics?: string;
  structureNotes?: string;
  imageReferences?: AudioAssetReference[];
  preferredFormat?: "mp3" | "wav";
  idempotencyKey?: string;
}

export interface MusicResult {
  audioBase64: string;
  mimeType: "audio/mp3" | "audio/wav";
  mode: MusicMode;
  durationSeconds: number;
  lyrics?: string;
  structure?: string;
  modelUsed: string;
  storageUrl?: string;
  storagePath?: string;
}

export type AudioGenerationRequest = VoiceoverRequest | MusicRequest;

export interface AudioGenerationResponse {
  success: boolean;
  generationType: AudioGenerationType;
  voiceoverResult?: VoiceoverResult;
  musicResult?: MusicResult;
  modelUsed: string;
  creditsCharged: number;
  newBalance?: number;
  fallbackUsed?: boolean;
  fallbackReason?: string;
  failoverState?: any;
}
