/**
 * Sales Inquiry Module Router.
 * Persists enterprise inquiries to PostgreSQL sales_leads table and dispatches notification.
 * Routes: POST /api/contact-sales
 */

import { Router } from "express";
import { salesRepository } from "../../repositories/salesRepository.js";

export const salesRouter = Router();

salesRouter.post(["/", "/contact-sales"], async (req, res) => {
  try {
    const { companyName, contactName, email, teamSize, message } = req.body;

    if (!companyName || !contactName || !email || !teamSize || !message) {
      return res.status(400).json({ error: "Missing required sales query parameters" });
    }

    // 1. Persist lead in PostgreSQL
    const leadRecord = await salesRepository.createLead({
      companyName,
      contactName,
      email,
      teamSize,
      message,
    });

    const mailTarget = process.env.BILLING_ALERT_EMAIL || "business@writopedia.com";
    const fromEmail = process.env.RESEND_FROM_EMAIL || "Writopedia <onboarding@resend.dev>";
    const resendApiKey = process.env.RESEND_API_KEY;

    let emailSent = false;
    let emailMessageId: string | null = null;

    if (resendApiKey) {
      try {
        const isTestSender = fromEmail.includes("onboarding@resend.dev");
        const toRecipients = isTestSender ? [mailTarget] : Array.from(new Set([mailTarget, "business@writopedia.com"]));

        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>New Enterprise / Contact Inquiry</title>
</head>
<body style="margin: 0; padding: 24px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #090d16; color: #f1f5f9;">
  <div style="max-width: 600px; margin: 0 auto; background: #0f172a; border: 1px solid #1e293b; border-radius: 12px; overflow: hidden;">
    <div style="background: linear-gradient(135deg, #dd1a46, #9b0b2c); padding: 20px 24px;">
      <h2 style="margin: 0; color: #ffffff; font-size: 20px; font-weight: 700; letter-spacing: -0.02em;">New Enterprise Inquiry</h2>
      <p style="margin: 4px 0 0; color: rgba(255,255,255,0.85); font-size: 13px;">Writopedia AI Platform · Lead Notification</p>
    </div>
    <div style="padding: 24px;">
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; width: 140px; font-weight: 600;">Contact Name:</td>
          <td style="padding: 8px 0; color: #ffffff; font-weight: 500;">${contactName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-weight: 600;">Email Address:</td>
          <td style="padding: 8px 0; color: #38bdf8;"><a href="mailto:${email}" style="color: #38bdf8; text-decoration: none;">${email}</a></td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-weight: 600;">Company / Brand:</td>
          <td style="padding: 8px 0; color: #ffffff;">${companyName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-weight: 600;">Team Size:</td>
          <td style="padding: 8px 0; color: #ffffff;">${teamSize}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-weight: 600;">Lead ID:</td>
          <td style="padding: 8px 0; color: #cbd5e1; font-family: monospace;">${leadRecord?.id || "N/A"}</td>
        </tr>
      </table>
      <div style="margin-top: 16px; padding: 16px; background: #182235; border-radius: 8px; border: 1px solid #334155;">
        <p style="margin: 0 0 8px; color: #94a3b8; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;">Requirements / Message:</p>
        <p style="margin: 0; color: #f8fafc; font-size: 14px; line-height: 1.6; white-space: pre-wrap;">${message}</p>
      </div>
      <p style="margin: 20px 0 0; color: #64748b; font-size: 11px;">Generated by Writopedia AI Platform Server at ${new Date().toUTCString()}</p>
    </div>
  </div>
</body>
</html>`;

        const response = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${resendApiKey.trim()}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            from: fromEmail,
            to: toRecipients,
            subject: `[Writopedia Lead] New Enterprise Query - ${contactName} (${companyName})`,
            html: htmlContent,
          }),
        });

        if (!response.ok) {
          const errorBody = await response.text();
          console.warn(`[SalesRoutes] Resend API error (${response.status}):`, errorBody);
        } else {
          const data = await response.json() as any;
          emailSent = true;
          emailMessageId = data?.id;
          console.log(`[SalesRoutes] ✅ Real lead email delivered to ${toRecipients.join(", ")} via Resend (ID: ${emailMessageId})`);
        }
      } catch (emailErr: any) {
        console.warn("[SalesRoutes] Failed to dispatch Resend lead notification:", emailErr?.message || emailErr);
      }
    }

    console.log("=================================================================");
    console.log(`✉️ SALES LEAD RECORDED`);
    console.log(`Lead ID        : ${leadRecord?.id || "N/A"}`);
    console.log(`To             : ${mailTarget}`);
    console.log(`From           : ${fromEmail}`);
    console.log(`Subject        : New Enterprise Query - ${companyName}`);
    console.log(`-----------------------------------------------------------------`);
    console.log(`Contact Person : ${contactName}`);
    console.log(`Contact Email  : ${email}`);
    console.log(`Company / Brand: ${companyName}`);
    console.log(`Est. Team Size : ${teamSize}`);
    console.log(`Resend Sent    : ${emailSent ? "YES (ID: " + emailMessageId + ")" : "NO / Simulated"}`);
    console.log(`Message Details:`);
    console.log(`"${message}"`);
    console.log("=================================================================");

    return res.json({
      success: true,
      leadId: leadRecord?.id,
      message: `Your custom sales request has been successfully dispatched. Our enterprise relations managers will follow up soon!`,
      details: {
        recipient: mailTarget,
        emailSent,
        timestamp: Date.now(),
      },
    });
  } catch (e: any) {
    console.error("Error processing contact sales request:", e);
    return res.status(500).json({ error: e.message || "Failed to dispatch sales query" });
  }
});
